version: '2.4'

services:
  app:
    platform: linux/x86_64
    restart: always
    build: ./
    volumes:
    - ioi_static:/usr/src/app/static/
    - ioi_media:/usr/src/app/media/
    depends_on:
    - postgres
    - redis
    environment:
      SECRET_KEY: 'secret_key_for_development_3969b4b149439648a52aa663bd740a4f'
      SESSION_COOKIE_SECURE: 0
      DB_HOST: postgres
      DB_USER: &db_user postgres
      DB_PASSWORD: &db_password postgres
      DB_NAME: &db_name ioitrans
      REDIS_HOST: redis
      REDIS_DB: 1
      GUNICORN_WORKERS: 2
      LOG_HANDLERS: 'file,stderr'


  nginx:
    restart: always
    build: ./nginx/
    ports:
    - 9000:80
    depends_on:
    - app
    volumes:
    - ioi_static:/usr/src/app/static/:ro
    - ioi_media:/usr/src/app/media/:ro

  postgres:
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - ioi_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ioitrans

  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_pgdata:
  ioi_static:
  ioi_media:
